
#ifndef SPATIAL_DATA_STRUCTURES_PROJECT_NEIGHBORHOOD_H
#define SPATIAL_DATA_STRUCTURES_PROJECT_NEIGHBORHOOD_H

///longitud , latitud en el json

class Neighborhood {

};


#endif //SPATIAL_DATA_STRUCTURES_PROJECT_NEIGHBORHOOD_H
